import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>AstroChrcha</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="/private">AstroChrcha</a>
          </h1>

          <p className={styles.description}>
            One stop solution htmlFor all your queries related to astro{" "}
          </p>
        </main>
      </div>
    </>
  );
}
